### PR TITLE
Revise method for filtering leg list page

### PR DESCRIPTION
**Pull request by dallasjc**
Goal: remove current filters and replace with five clickable images that have corresponding filters: us map, state map, local icon, liquid logo for liquid bills, and capitol building icon for legislative bills
image

Added leg name to Introduced in info as we will show bills from multiple legislatures on the same screen
image

Specced out as Phase 1 here: 
https://docs.google.com/document/d/10f0IbyVSm-tqhVTGYyzihxFV3ORLnqTc7eHYz_RW2ac/edit

### CODE REVIEW

**Comment by dallasjc** [comment]
everything is functional, but I'm having trouble getting the images and text to center:

image

**Comment by dallasjc** [comment]
Also need to figure out how to split row at "Introduced by" on mobile without splitting on desktop
image

**Comment by dallasjc** [comment]
[ ] Enable imported and liquid legislation to be sorted together. I tried to use &or on the front end, but didn't work. Best guess is we should add created_at date to last_action_at date

**Comment by dallasjc** [comment]
I revised the original design to downplay the filters after talking to Josh, then I tried using buttons and liked the result. There are two outstanding fixes before this is ready:

[] make it so that the filters stack correctly on mobile
image
[] make it so liquid and legislature bills sort together correctly. probably requires adding created_at to last_action_at in backend

**Comment by dallasjc** [comment]
Still need images for other states

**Comment by dallasjc** [comment]
I switched it so that this uses flag maps (which we already have) instead of basic state maps, which means we no longer need to grab all 50 states. This pr is ready to go

**Comment by alexmingoia** [comment]
Closing this as it's no longer relevant with the `/activity` page.

**Pull request closed without merging**
