### PR TITLE
Changed description for bill measures

### PR DESCRIPTION
**Pull request by dallasjc**
New language: Discuss with your fellow voters & be heard by your elected officials.

### CODE REVIEW

**Comment by dsernst** [comment]
Can you explain why this wording is an improvement?

**Comment by dallasjc** [comment]
Shorter and to the point - says most of the same thing without going into
details. This frees up space to either make the text bigger or add a bit of bill
description
Envisioning it from their pov, they don't want to know what the whole website is
for, they just want to know more about what happens if they click the link.
Also, the last sounds like it's referring to scorecards which we're moving away
from
On Mon, Dec 10, 2018 at 5:23 PM David Ernst <notifications@github.com> wrote:
Can you explain why this wording is an improvement?

**Comment by dallasjc** [comment]
Do you have a reason you prefer the current language? I wrote it and I wince every time I see it heh -overly long and just awkward to talk about state and federal bills when the question is about Madison and vice-versa.

**Comment by dsernst** [comment]
Ok— sorry it took me so long but I've come around to see your point. 

I manually merge in the commit for the social media card description change. (Now in upstream/master: https://github.com/voteliquid/liquid.us/commit/e6122a5f9dde56d1ebf0fceea82b383bb38fe196)

Not sure what's with the other commit, but closing this PR for now.

**Pull request closed without merging**
