### PR TITLE
Social language

### PR DESCRIPTION
**Pull request by dallasjc**
Revises current language for comment title "Dallas voted yes/no on {leg name}: {measure_title}" to "Dallas Cole: tell Congress to vote no on {measure_title}"

On htmlwrapper:

if a comment, this code splits the title at "on," creating two new variables. commentBill for bill title and commentPosition one for the user's position.

Added code to replace page_title with commentBill for comments

I couldn't figure out where I should insert commentPosition. Should be a separate line between the bill title and the comment/page_description. May work to do it by adjusting the description on either page, but I don't recognize the format so I'm unsure how to create a line break between them.

Why do this? Including their position and the bill name in one line means either that users don't get enough info about the bill title or can't see the comment, like so:

image

### CODE REVIEW

**Comment by dsernst** [comment]
Hmmm, ok. 

👍I like the changes to CommentPage's `<title>`

**Comment by dsernst** [comment]
😕The `indexOf` checks in HtmlWrapper are pretty brittle... 

It's not impossible to imagine this could lead to false positives, whenever a bill title or person's name includes the characters "tell" or "on " anywhere in them. 

So the name "Ron ", for example, would create a problem.

**Comment by dsernst** [comment]
I don't understand the question about inserting `commentPosition`. Can you give an example of exactly what you want the card to look like?

**Comment by dsernst** [comment]
⚠️ the [string.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) method is deprecated

image

**Comment by dsernst** [comment]
Doesn't look like newlines are possible in Facebook cards (see comments under the question): https://stackoverflow.com/questions/38915370/how-to-share-content-with-newline-on-facebook-using-og-graph-tags

https://stackoverflow.com/questions/7348980/facebook-send-dialog-adding-a-linebreak-in-the-description

**Comment by dsernst** [comment]
( I pushed up some very minor cleanup to this branch, fyi— )

**Comment by dallasjc** [comment]
Good to know about the newlines, thanks. Prepped the example below based on
that response, basically putting the vote position at the front of the
description.







On Wed, Feb 6, 2019 8:41 PM, David Ernst notifications@github.com  wrote:
( I pushed up some very minor cleanup to this branch, fyi— )

**Comment by dallasjc** [comment]
at least one bug in that last commit, working on it

**Comment by dsernst** [comment]
@dallasjc what's the state of this?

**Comment by dallasjc** [comment]
I was waiting for you to finish making changes to the card as shown below. I
was never able to figure out how to test social media locally, but it should all
be ready except for adding the "Miriam Stone: Tell Congress to vote no." before
the comment.

I'd take a guess, but both spots where I think you can add it use code
formatting I'm not familiar with
Comment page:  this.setState({ loading_measure: false, page_title, 
page_description: this.escapeHtml(comment.comment, { replaceAmp: true }), 
og_image_url: ogImage, measures: { ...this.state.measures, [measure.short_id]: {
 ...this.state.measures[measure.short_id], ...measure
HTML Wrapper:        <meta property="og:title" content="${wi_image ? `Wisconsin
Legislation` : title.replace(/</g, '&lt;').replace(/"/g, '&quot;')}" /> <meta
property="og:description" content="${wi_image ? `Vote now on extraordinary
session bills.` : description.replace(/</g, '&lt;').replace(/"/g, '&quot;')}" />
 <meta property="og:image" content="${og_image_url}" /> <meta property="og:type"
content="website" />
On Thu, Feb 7, 2019 at 9:32 AM David Ernst <notifications@github.com> wrote:
@dallasjc  what's the state of this?

**Comment by dsernst** [comment]
Merged. 

I also did some minor code cleanup: https://github.com/voteliquid/liquid.us/commit/bf840865f72f08b41723bd984a79a72619ae919a and https://github.com/voteliquid/liquid.us/commit/7d84d864de3cb707dce780bb0dd855f92f399085.

And then added code to strip the image urls out of the `og:descriptions`: https://github.com/voteliquid/liquid.us/commit/5687bc761439d0a3a5d718b6f246507c30d14bfa

**Comment by dallasjc** [comment]
Looking pretty good, but the sidebar links still aren't workingFixed here
Did you fix the broken image for the hold charter schools accountable? That page
wasn't loading an image at all on the twitter checker earlier, but now it's
working.  





On Sat, Feb 9, 2019 2:12 AM, David Ernst notifications@github.com  wrote:
Merged.

I also did some minor code cleanup: bf84086  and 7d84d86.

And then added code to strip the image urls out of the og:descriptions: 5687bc7

**Comment by dsernst** [comment]
Hey FYI— when you use the reply to github via email tool, all the links get stripped out. So "Fixed here", for example. Guessing that's https://github.com/voteliquid/liquid.us/pull/101?

And yeah, it now uses the comment's first inline image, if there is one, as the `og:image`: https://github.com/voteliquid/liquid.us/commit/dde049c1185f864f4f52c72597a8d8a1acd4634d

**Comment by dallasjc** [comment]
Gotcha, good to know. Thanks!  





On Mon, Feb 11, 2019 5:41 PM, David Ernst notifications@github.com  wrote:
Hey FYI— when you use the reply to github via email tool, all the links get
stripped out. So "Fixed here", for example. Guessing that's #101?

And yeah, it now uses the comment's first inline image, if there is one, as the 
og:image: dde049c

**Pull request merged**
