### PR TITLE
Bug: Congress image fix not showing on bill social (for review, micro help needed)

### PR DESCRIPTION
**Pull request by dallasjc**
Images for states worked and cities continue to work, but Congress images are not working. Couple possible reasons, but easiest solution was to tell the constant to ignore congressional bills as well as city ones

### CODE REVIEW

**Comment by dallasjc** [comment]
I tested this via console.log

**Comment by dsernst** [comment]
I don't understand what this means, can you clarify? Is this fixing an ongoing bug? A screenshot would help.

**Comment by dallasjc** [comment]
image

**Comment by dallasjc** [comment]
had an issue merging the comment page. Tried copying over the version from the master, but it's treating it as if it's all new code. Due to changes in the code, the revisions I offered on comment page should be reverted so that it matches the live version on the website

**Pull request closed without merging**
