### PR TITLE
Add ability to ask & endorse questions through petition page

### PR DESCRIPTION
**Pull request by dallasjc**
Goal: Allow people to ask, review & sort questions on Petition page
Deadline: July 17th, 2019

Specced out here: https://docs.google.com/document/d/1hhEVX7LbxiYBKby5hnW1ti6R_-wx-ianwDLyQNHa_-I/edit

I made one change to the spec, using checkboxes to determine private/public instead of the dropdown menu. Let me know if I should revert

- [x] Created Comments & Questions tab
- [x] Added Sort by box
- [x] Added Question button
- [x] Created add question form, with sign up boxes when logged out

- [x] Make Add question button live, so form is hidden until clicked
- [ ] Save data from question form
- [ ] Pull questions into questions tab
- [ ] Add endorse buttons
- [ ] Ensure Sort by Most Recent & Most support options are working

Logged in, on desktop
image

Logged out, via mobile
image

### CODE REVIEW

**Comment by alexmingoia** [comment]
An API for questions is live: `/questions`, `/questions_votes`, and `/questions_detailed` (includes vote count, user profile).

I'm still working on the UI. I should be done soon.

**Comment by dallasjc** [comment]
Nice! Were you able to finish it? How do I see it on the site if so?  





On Fri, Jul 19, 2019 6:07 AM, Alex Mingoia notifications@github.com  wrote:
An API for questions is live: /questions, /questions_votes, and 
/questions_detailed  (includes vote count, user profile).

I'm still working on the UI. I should be done soon.

**Comment by alexmingoia** [comment]
I got a very rushed version deployed with https://github.com/voteliquid/liquid.us/pull/160

**Comment by dallasjc** [comment]
Awesome, thanks for the update & your work on this  





On Fri, Jul 19, 2019 11:56 PM, Alex Mingoia notifications@github.com  wrote:
I got a very rushed version deployed with #160

**Pull request closed without merging**
