### PR TITLE
Add link to bottom of summaries/bill descriptions

### PR DESCRIPTION
**Pull request by dallasjc**
Bills without a summary have an immediate link to Congress.gov, but those that do have a summary have no such link.

 This pull request adds that link at the end and text: Learn more at Congress.gov.

Tested it on my local server and it works fine

### CODE REVIEW

**Comment by dsernst** [comment]
Can you add a screenshot to this PR?

**Comment by dallasjc** [comment]
image

**Comment by dsernst** [comment]
Looks like there's an issue with the FontAwesome external link?

This code:

```html
<span class="icon is-small"><i class="fa fa-external-link"></i></span>
```

Isn't showing up in your screenshot?

**Comment by dsernst** [comment]
This is also showing up on local legislation, e.g.:

http://localhost:3000/joshuakrafchin/legislation/epic-charter-renewal

image

**Comment by dallasjc** [comment]
Not sure what you're saying - the font of the links are off? Not sure what the impact of that code is supposed to be

**Pull request merged**
