### PR TITLE
Leg list revised

### PR DESCRIPTION
**Pull request by dallasjc**
image

image

Made a number of changes to the leg list page.

**Removed current menus and created filters for jurisdiction, status, type, etc.** 

- Filters hidden by default behind a button.

- One of the filters is Resolutions, as some have been imported from states. However there is a bug preventing most from being properly identified as such. Therefore this Resolutions filter is not very useful right now.

  - Once we import Congress resolutions, they ought to fit right in.

Therefore, we should either:
- [x] hide the Resolution checkbox for now.

or
 
- [ ] fix Resolutions on the state level or import national Resolutions.

**Revised leg list card details to make it more user-friendly.** 

- Too much white-space currently - have to look from left to right to see the super small vote button

- Added Introduced summary bar at bottom

  - This Introduced bar works for now, but may go over one line if the name is too long. 
 
David and I found a module to measure string width based on characters. Thus if the string is too long, this ought to use a smaller font size.

- [x] **But**, this code is not fully working yet. I need to fix it before we merge.

### CODE REVIEW

**Comment by dallasjc** [comment]
Sorting by referendum for WI doesn't work - only one referendum is recognized as such by type. I'd suggest either removing referendum as a checkbox for now (which I can do, let me know) or going into the backend to tell it to evaluate the title for AJR, SJR, SR, AR, etc and mark those as type = referendum (which I can't do)

**Comment by dsernst** [comment]
- [ ] Need to resolve Merge Conflict with master

**Comment by dallasjc** [comment]
Outstanding:
- [ ] fix url bar to allow specifying different legislatures
- [ ] fix size of summary tooltip button
- [ ] fix left margin on filter list for mobile
- [ ] remove filters tabs unnecessary function
- [ ] add margin above filter buttons below navbar on mobile
- [ ] fix summary bar dynamic sizing

**Comment by dallasjc** [comment]
- [ ] fix url bar to allow specifying different legislatures
I've set it so that if you change state=on to state=CA, but it doesn't work for cities. I also can't figure out how to change the default value from 'on' to WI/Madison,%20WI

- [x] fix summary bar dynamic sizing
I couldn't fix this with dynamic sizing, but I reworked the presentation so it doesn't matter

**Pull request closed without merging**
