### PR TITLE
add support for Microsoft Windows environment with howto instructions in README

### PR DESCRIPTION
**Pull request by kxrom**
* New file `.template.env.bat` for Microsoft Windows environment.
* Update `README` with instructions for local development on Microsoft Windows.

### CODE REVIEW

**Comment by dsernst** [comment]
Is there a way to programmatically copy the values? Instead of having two sources of truth, that could easily get out of sync

**Comment by domi41** [comment]
I know of [Gulp](https://gulpjs.com/) for these things, if that can help.

**Comment by domi41** [comment]
A `Makefile` might do the jab as well.

**Comment by kxrom** [comment]
The following script does some of the job, but there are still two difficulties: 

- handling  the variables depending on another variable ; 
- handling local/global environment. (_workaround: we could write in a new file .your.env.bat that would be executed at the end of the script_)

Do you have any idea on what should be done?

```
@echo off
Setlocal EnableDelayedExpansion

for /f "tokens=1,2" %%a in (.template.env) do (
  IF "%%a" == "export" for /f "tokens=1,2 delims==" %%a in ("%%b") do (
    set var=%%a
    set val=%%b
    set !var!=!val:~1,-1!
    echo set !var!=%!var!%
  )
)

echo ---------Test local env:---------------------
echo Test: NODE_ENV = %NODE_ENV%

endlocal

echo ---------Test global env:---------------------

echo Test: NODE_ENV = %NODE_ENV%

```

**Comment by mose** [comment]
Maybe it would make sense to use the [dotenv npm package](https://www.npmjs.com/package/dotenv), (just wondering, maybe it was considered before)?

**Comment by kxrom** [comment]
> 
> 
> Maybe it would make sense to use the [dotenv npm package](https://www.npmjs.com/package/dotenv), (just wondering, maybe it was considered before)?

Or a short howto on the README so that we remove the *.bat file from the project?

**Pull request merged**
